CARGO = cargo
OPEN = open

build:
	$(CARGO) build

check:
	$(CARGO) check

fmt:
	$(CARGO) fmt

gql_playground:
	${OPEN} http://localhost:4000/playground

release:
	$(CARGO) build --release

run:
	$(CARGO) run
